Trait {
	#name : #TDAPProtocolVisitor,
	#category : #'DebugAdapterProtocol-Visitors'
}

{ #category : #visiting }
TDAPProtocolVisitor >> visitAttachRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitAttachRequestArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitAttachResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitBreakpoint: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitBreakpointEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitBreakpointLocation: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitBreakpointLocationsArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitBreakpointLocationsRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitBreakpointLocationsResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitCancelArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitCancelRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitCancelResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitCapabilities: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitCapabilitiesEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitChecksum: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitChecksumAlgorithm: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitColumnDescriptor: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitCompletionItem: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitCompletionItemType: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitCompletionsArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitCompletionsRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitCompletionsResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitConfigurationDoneArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitConfigurationDoneRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitConfigurationDoneResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitContinueArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitContinueRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitContinueResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitContinuedEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDataBreakpoint: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDataBreakpointAccessType: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDataBreakpointInfoArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDataBreakpointInfoRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDataBreakpointInfoResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDebugpyAttachEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDebugpyWaitingForServer: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDebugpyWaitingForServerEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDisassembleArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDisassembleRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDisassembleResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDisassembledInstruction: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDisconnectArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDisconnectRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitDisconnectResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitErrorResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitEvaluateArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitEvaluateRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitEvaluateResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitExceptionBreakMode: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitExceptionBreakpointsFilter: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitExceptionDetails: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitExceptionFilterOptions: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitExceptionInfoArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitExceptionInfoRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitExceptionInfoResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitExceptionOptions: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitExceptionPathSegment: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitExitedEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitFunctionBreakpoint: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitGotoArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitGotoRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitGotoResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitGotoTarget: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitGotoTargetsArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitGotoTargetsRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitGotoTargetsResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitIPAddress: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitInitializeRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitInitializeRequestArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitInitializeResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitInitializedEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitInstructionBreakpoint: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitInvalidatedAreas: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitInvalidatedEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitLaunchRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitLaunchRequestArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitLaunchResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitLoadedSourceEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitLoadedSourcesArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitLoadedSourcesRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitLoadedSourcesResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitMessage: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitModule: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitModuleEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitModulesArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitModulesRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitModulesResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitModulesViewDescriptor: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitNextArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitNextRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitNextResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitOutputEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitPauseArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitPauseRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitPauseResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitProcessEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitProgressEndEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitProgressStartEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitProgressUpdateEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitProtocolMessage: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitPythonAttachRequestArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitReadMemoryArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitReadMemoryRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitReadMemoryResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitRestartArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitRestartFrameArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitRestartFrameRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitRestartFrameResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitRestartRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitRestartResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitReverseContinueArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitReverseContinueRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitReverseContinueResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitRunInTerminalRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitRunInTerminalRequestArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitRunInTerminalResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitScope: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitScopesArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitScopesRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitScopesResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetBreakpointsArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetBreakpointsRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetBreakpointsResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetDataBreakpointsArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetDataBreakpointsRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetDataBreakpointsResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetExceptionBreakpointsArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetExceptionBreakpointsRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetExceptionBreakpointsResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetExpressionArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetExpressionRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetExpressionResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetFunctionBreakpointsArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetFunctionBreakpointsRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetFunctionBreakpointsResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetInstructionBreakpointsArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetInstructionBreakpointsRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetInstructionBreakpointsResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetVariableArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetVariableRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSetVariableResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSource: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSourceArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSourceBreakpoint: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSourceRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSourceResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStackFrame: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStackFrameFormat: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStackTraceArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStackTraceRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStackTraceResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStepBackArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStepBackRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStepBackResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStepInArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStepInRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStepInResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStepInTarget: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStepInTargetsArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStepInTargetsRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStepInTargetsResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStepOutArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStepOutRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStepOutResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitSteppingGranularity: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitStoppedEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitTerminateArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitTerminateRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitTerminateResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitTerminateThreadsArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitTerminateThreadsRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitTerminateThreadsResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitTerminatedEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitThread: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitThreadEvent: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitThreadsRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitThreadsResponse: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitValueFormat: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitVariable: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitVariablePresentationHint: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitVariablesArguments: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitVariablesRequest: anObject [

	^ false halt
]

{ #category : #visiting }
TDAPProtocolVisitor >> visitVariablesResponse: anObject [

	^ false halt
]
